// src/components/Nav.vue
<template>
  <nav class="nav">
    <router-link to="/money" class="item">
     <Icon name="money"/>
      记账
    </router-link>
    <router-link to="/labels" class="item">
      <Icon name="label"/>
      标签
    </router-link>
    <router-link to="/statistics" class="item">
      <Icon name="statistics"/>
      统计
    </router-link>
  </nav>
</template>

<script lang="ts">

  export default {
    name: 'Nav'
  };
</script>

<style lang="scss" scoped>
  nav{
    font-size: 15px;
    /*border: 1px solid red;*/
    display: flex;
    box-shadow: 0 0 3px rgb(0,0,0,0.25);
    flex-direction: row;
    > .item{
      padding: 2px;
      width: 33.33333%;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      .icon{
        height: 34px;
        width: 34px;
      }
    }
  }

</style>

// src/components/Nav.tsx
import styled from 'styled-components';
import {Link} from 'react-router-dom';
import React from 'react';
import Icon from './Icon';



const NavStyle = styled.nav`
box-shadow: 0 0 3px rgba(0,0,0,0.25);
  >ul{
    display:flex;
    flex-direction: row;
    >li{
      width: 33.33333%;
      text-align: center;
      padding: 2px 0;
      display:flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
    };
  }
`
const Nav = ()=>{
  return(
    <NavStyle>
      <ul>
        <li>
          <Icon name='label'/>
          <Link to="/labels">labels</Link>
        </li>
        <li>
          <Icon name='money'/>
          <Link to="/money">money</Link>
        </li>
        <li>
          <Icon name="statistics"/>
          <Link to="/statistics">statistics</Link>
        </li>
      </ul>
    </NavStyle>
  )
}

export default Nav;
